FROM ubuntu

RUN apt-get update \
    && apt-get -y install python libpython2.7-dev ipython python-setuptools python-pip libmysqlclient-dev python-mysqldb

RUN pip install ZODB ZEO Persistence
RUN echo mysql-server mysql-server/root_password password root | debconf-set-selections;
RUN echo mysql-server mysql-server/root_password_again password root | debconf-set-selections;
RUN apt-get -y install mysql-server
RUN pip install sqlalchemy PyMySQL

#service mysql start
